# Generated by Django 6.0.1 on 2026-01-22 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0006_alter_empresa_teste_ate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preapproval_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('authorized', 'Autorizado/Ativo'), ('paused', 'Pausado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_detalhes', to='logistica.empresa')),
            ],
            options={
                'verbose_name': 'Assinaturas Mercado Pago',
            },
        ),
        migrations.CreateModel(
            name='HistoricoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pagamentos.assinaturamp')),
            ],
        ),
    ]
