# Generated by Django 4.2.27 on 2026-01-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_alter_assinaturamp_id_alter_historicopagamento_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=255)),
                ('corpo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Sucesso', 'Sucesso'), ('Erro', 'Erro')], max_length=20)),
                ('erro_detalhe', models.TextField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de E-mail',
                'verbose_name_plural': 'Logs de E-mail',
                'ordering': ['-data_envio'],
            },
        ),
    ]
