# Generated by Django 6.0.1 on 2026-01-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caminhao',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=13.0, max_digits=5, verbose_name='Porcentagem de Comissão (%)'),
        ),
    ]
