# Generated by Django 6.0.1 on 2026-01-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_caminhao_comissao_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caminhao',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=13.0, max_digits=5, verbose_name='Comissão (%)'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='motorista',
            field=models.CharField(default='//', max_length=100, verbose_name='Motorista'),
        ),
    ]
