# Generated by Django 6.0.1 on 2026-01-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_alter_caminhao_comissao_percentual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['id']},
        ),
    ]
