# Generated by Django 6.0.1 on 2026-01-22 22:04

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_alter_despesa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='assinatura_ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='teste_ate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 25, 22, 4, 26, 806974, tzinfo=datetime.timezone.utc)),
        ),
    ]
