# Generated by Django 6.0.1 on 2026-01-22 22:08

import logistica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0005_empresa_assinatura_ativa_empresa_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='teste_ate',
            field=models.DateTimeField(default=logistica.models.tres_dias_depois),
        ),
    ]
