# Generated by Django 6.0.1 on 2026-01-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0006_alter_empresa_teste_ate'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='limite_veiculos',
            field=models.IntegerField(default=2),
        ),
    ]
