# Generated by Django 6.0.1 on 2026-01-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0008_alter_perfilusuario_empresa'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['caminhao', 'data'], name='logistica_d_caminha_bd2e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['data'], name='logistica_d_data_6cc9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='viagem',
            index=models.Index(fields=['caminhao', 'data'], name='logistica_v_caminha_d56e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='viagem',
            index=models.Index(fields=['data'], name='logistica_v_data_422bba_idx'),
        ),
    ]
