# Generated by Django 4.2.27 on 2026-01-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0009_despesa_logistica_d_caminha_bd2e7f_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['-data', '-km_atual']},
        ),
        migrations.AlterModelOptions(
            name='viagem',
            options={'ordering': ['-data', '-id']},
        ),
    ]
